# Generated by Django 2.1 on 2018-08-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Alias')),
            ],
            options={
                'verbose_name': 'Programming language',
                'verbose_name_plural': 'Programming languages',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.IntegerField(choices=[(0, 'Elementary'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Nightmare')], default=1)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rating ')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Language', verbose_name='Language')),
            ],
        ),
    ]
