# Generated by Django 2.1.2 on 2018-11-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180914_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(blank=True, max_length=255, null=True, verbose_name='Repository URL')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Maintainer',
                'verbose_name_plural': 'Maintainers',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='packagerequest',
            options={'ordering': ['-pk'], 'verbose_name': 'Package request', 'verbose_name_plural': 'Package requests'},
        ),
        migrations.AddField(
            model_name='maintainer',
            name='package_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PackageRequest', verbose_name='Parent'),
        ),
    ]
